<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Amazon_TestSuite_ValidateSearchFieldItem_002</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>5de9cb5b-dd2b-4b53-8a7c-00451ad2c35a</testSuiteGuid>
   <testCaseLink>
      <guid>85ebebff-2736-451a-bd92-dc69a097ecde</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Amazon_ValidateSearchFieldItem_002</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2907998d-ea61-4875-9c6d-22555e74b692</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData/Amazon_TestData/Amazon_TestData_ValidateSearchFieldItem_002</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2907998d-ea61-4875-9c6d-22555e74b692</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>category</value>
         <variableId>9b8d0848-f7ec-41aa-bbab-2eef945ac1f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2907998d-ea61-4875-9c6d-22555e74b692</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Item</value>
         <variableId>ed084f91-ae21-4ed7-8225-9f9279082521</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
