<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Amazon_TestSuite_Login_001</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>644be704-ca3a-426e-8af2-16fd48559b38</testSuiteGuid>
   <testCaseLink>
      <guid>8bd2fb32-6c99-401a-bfc1-f20e9cdfaec1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC_Amazon_Login_001</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d7ad2a93-e511-4874-a8a8-5470d645c8bf</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData/Amazon_TestData/Amazon_TestData_Login_Excel1</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d7ad2a93-e511-4874-a8a8-5470d645c8bf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>98bdcff2-7f59-4d84-b0fb-1916fef02c6d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d7ad2a93-e511-4874-a8a8-5470d645c8bf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>31243bc8-2455-4cfc-a92a-488b51d73009</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
